### ISSUE TITLE
[Add]: Adding a button

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#1]
Add a button in the buttons folder that you liked. Be sure to not break the structure of the project.

**Comment by Utkarsh750** [comment]
Hello Parag as I am a newbie in open source please have a look once I pull the request ,
please notify and guide me if I do some errors

**Comment by parag477** [comment]
Go ahead mate! I am there to help you..

**Comment by Typical-techno** [comment]
Can I also add a button?
As I am a Newbie, don't know much of open source contributions

**Comment by IndranjanaChatterjee** [comment]
I would like to work on this issue. Can U pls assign it to me under hacktoberfest23

**Comment by parag477** [comment]
> Can I also add a button? As I am a Newbie, don't know much of open source contributions

You have to open a new issue

**Comment by Typical-techno** [comment]
> Add a button in the buttons folder that you liked. Be sure to not break the structure of the project.

Sir, I Have Raised a pull request as per the issue.
Is this okay? or do I have to do something else?

**Comment by IndranjanaChatterjee** [comment]
> Add a button in the buttons folder that you liked. Be sure to not break the structure of the project.

I would like to work on this issue. Can U pls assign it to me so that I can also add a new button under hacktoberfest23

**Comment by Typical-techno** [comment]
I Have Raised The PR For Adding the Button Please Merge It.

**Comment by parag477** [comment]
Merged 👍 @Typical-techno
