### ISSUE TITLE
[Hacktoberfest]: Add a radio button

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#12]
Add a new radio buttton to this repository

**Comment by aahanatiwari** [comment]
i would like to participate. please assign me this issue.

**Comment by Utkarsh750** [comment]
hello Sir, please assign me to this issue

**Comment by parag477** [comment]
@aahanatiwari assigned to you

**Comment by Utkarsh750** [comment]
Hello sir please check my PR and merge it if it meets the condition of
merge
I have raised a PR for adding new button as it is my first open source
contribution

Github I'd - Utkarsh750

Regards
Utkarsh Sharma

**Comment by Anshita100** [comment]
Hello ,Pls assign me this issue

**Comment by KESHAV4R3** [comment]
hii @parag477 can u plz assign this issue to me, as i can add a radio button in a new and iconic way
