### ISSUE TITLE
Add a button

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#131]
I want someone who can add a button in this repository.

**Comment by manan18** [comment]
Your project looks interesting and innovative , I would really like to work on it.
Can you please assign me this issue?

**Comment by Dipanshu018** [comment]
parag477 in which folder of code

**Comment by parag477** [comment]
@PeeyushRathore merging

**Comment by parag477** [comment]
@manan18 assigning you

**Comment by Dipanshu018** [comment]
sir please assign me and merge my pr under hacktoberfest label
i already created pr request
