### ISSUE TITLE
[Hacktoberfest]: Add a input box

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#14]
Add a new input box in this repository

**Comment by roniskywalker** [comment]
Hello [parag477](https://github.com/parag477) I want to work with this issue. Please assign me.

**Comment by ujjwalshivhare** [comment]
Hello sir,
can you assign me this issue ?
I am newly in open source . So i would like to start my first contribution from this..

**Comment by parag477** [comment]
go ahead @ujjwalshivhare assigned to you

**Comment by manoj8861** [comment]
Hi, can i attempt as well ? please assign it to me as well?

**Comment by parag477** [comment]
Your PR merged @manoj8861
