### ISSUE TITLE
Add a new form

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#146]
Add a new form in the forms folder.

**Comment by devharsh007** [comment]
Assign me, I'll add it.

**Comment by parag477** [comment]
Great @devharsh007 assigning you

**Comment by dakshsinghrathore** [comment]
@parag477 seems like @devharsh007 has bailed out, would love to work on this issue kindly, assign this issue to me.

**Comment by chinmayborade** [comment]
hello I am interested in this task

**Comment by praveen88p** [comment]
Hey I want to contribute to this  repo. Please assign me this.
