### ISSUE TITLE
[Hacktoberfest]: Add a card

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#15]
Add code of a card in this repository

**Comment by Surajit0573** [comment]
I can do this please assign me.

**Comment by parag477** [comment]
@Surajit0573 assigned to you

**Comment by Jagannath15** [comment]
assign me . i can do it

**Comment by parag477** [comment]
@Jagannath15  you can do as well. Assigning you

**Comment by parag477** [comment]
Merged @Surajit0573
