### ISSUE TITLE
[Hacktoberfest]: Adding a button

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#16]
Add code of a button in this repository

**Comment by whysatyam** [comment]
I'll work on it , kindly assign me this task @parag477

**Comment by parag477** [comment]
@whysatyam go ahead !!

**Comment by Utkarsh750** [comment]
hello, sir I have raised a PR please check and merge it.

**Comment by VinayakGaikwad101** [comment]
Hi! Assign me this issue, I'll fix it :)

**Comment by Chandan-0320** [comment]
HI @parag477  please assign me the task I'll fix it.

**Comment by Anshita100** [comment]
Hello ,Pls assign me this issue

**Comment by Dhairyaa2004** [comment]
kindly assign me the issue.

**Comment by parag477** [comment]
Merged @whysatyam
