### ISSUE TITLE
[Hacktoberfest]: Add a new component

### ISSUE THREAD

**Issue by parag477** [parag477/Amazing-Webdev-Components#17]
Add a new component

**Comment by Infinite-Null** [comment]
sir I have raised an Issue and made a pull request

**Comment by roniskywalker** [comment]
Hello [parag477](https://github.com/parag477), I want to work with this issue. Please assign me.

**Comment by ujjwalshivhare** [comment]
Hello sir,
please assign me this issue .

**Comment by parag477** [comment]
@ujjwalshivhare assigned to you

**Comment by parag477** [comment]
Merged @ujjwalshivhare
