### ISSUE TITLE
Make a Responsive Top Nav Bar

### ISSUE THREAD

**Issue by Saroj-pradhan** [parag477/Amazing-Webdev-Components#36]
Mobile-Friendly Layout: create & Adjust the layout of the navigation bar to ensure it stacks vertically on smaller screens, like mobile phones. This may involve reordering or hiding some elements to prioritize essential navigation links.

Media Queries: Use CSS media queries to apply specific styles for different screen sizes. This includes adjusting font sizes, padding, and margins to improve readability and usability on smaller screens.

Burger Menu: Consider implementing a hamburger menu for extremely narrow screens. This can provide a compact menu that expands when clicked, saving space while maintaining access to all navigation links

**Comment by parag477** [comment]
Yes you can make a new folder "Navbar" and start your contribution in the folder "navbar1" that you will create. Assigning you @Saroj-pradhan
