### ISSUE TITLE
Create Footer Section  

### ISSUE THREAD

**Issue by Saroj-pradhan** [parag477/Amazing-Webdev-Components#37]
create a footer section which include github , linkedin , twitter , instagram . 
you don't need to provide any link to the footer .

**Comment by malpani2003** [comment]
please assign me

**Comment by AdityaSherki** [comment]
Please assign me this task.

**Comment by Virtual4087** [comment]
Hi please check my pr

**Comment by parag477** [comment]
@Virtual4087 your pr merged ✔️
