### ISSUE TITLE
adding search_button.html files to buttons folder

### ISSUE THREAD

**Issue by Saroj-pradhan** [parag477/Amazing-Webdev-Components#38]
1.  add the  search_button.html  files to the buttons folder 
     this is for first time contributor .

<img width="169" alt="Screenshot 2023-10-03 130618" src="https://github.com/parag477/Amazing-Webdev-Components/assets/119152425/8b0fe152-7ea6-4fff-a157-17f7f1106591">

**Comment by parag477** [comment]
@CoderRedwing pr merged
