### ISSUE TITLE
html_card

### ISSUE THREAD

**Issue by Palak4620** [parag477/Amazing-Webdev-Components#42]

**Comment by KESHAV4R3** [comment]
hii , @parag477 please assign this issue to me as it seems to be a perfect fit for my first open source contribution

**Comment by parag477** [comment]
Okay @KESHAV4R3 you can work on it

**Comment by KESHAV4R3** [comment]
so can u plz elaborate that what kind of html card i need o make .Does i need to change the design or make a new card with me additional features

**Comment by parag477** [comment]
You need to add a new card in the cards folder

**Comment by KESHAV4R3** [comment]
hii @parag477 #htmlcard is almost ready and till midnight i will give it to u , and sorry for the delay as my midsem was going on.......
