### ISSUE TITLE
add a form to your repository 

### ISSUE THREAD

**Issue by anxantt** [parag477/Amazing-Webdev-Components#44]
you need to add a form to your repository its missing and I would love to add it

**Comment by parag477** [comment]
I will merge the request of the first one to open the pull request.

**Comment by purnasth** [comment]
Hello, feel free to give me this assignment. Also, could you be more specific about the kind of form that has to be placed here.

**Comment by parag477** [comment]
Great work @NegativE333 Merging tour PR. Have a good day!!
