### ISSUE TITLE
[feat]: Add a Preloader Component

### ISSUE THREAD

**Issue by purnasth** [parag477/Amazing-Webdev-Components#57]
## Description:
Requesting the addition of a preloader component to enhance user experience in our web development components collection.

**Comment by purnasth** [comment]
Hello, feel free to assign this task to me.

**Comment by parag477** [comment]
@purnasth assigned to you

**Comment by parag477** [comment]
@purnasth nice work keep going. Merged your PR

**Comment by purnasth** [comment]
Is it alright if I again open an another PR to upload a different preloader?

**Comment by parag477** [comment]
Merged @purnasth Thankls for contributing 👍
