### ISSUE TITLE
adding a button

### ISSUE THREAD

**Issue by vishalsinghtanwar** [parag477/Amazing-Webdev-Components#68]
i want a add a new modern button

**Comment by parag477** [comment]
@vishalsinghtanwar go ahead assigning you

**Comment by Anshita100** [comment]
Assign me this issue

**Comment by PeeyushRathore** [comment]
Please assign me this issue

**Comment by GeeekySouro003** [comment]
Hello sir i will be very grateful if i get the oppurtunity to work on this.Please assign me on this.
